name: Scrape Anichin Anime List & Video

on:
  push:
  pull_request:
  workflow_dispatch: # Bisa dijalankan manual dari GitHub UI
  schedule:
    - cron: '0 3 * * *' # (opsional) jalan setiap hari jam 3 pagi UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    # --- PERBAIKAN DI SINI ---
    # "contents: write" harus menjorok ke dalam (indent)
    # di bawah "permissions:"
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Disarankan menggunakan versi terbaru

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      - name: Run scraping script
        # Tidak perlu | jika hanya satu baris
        run: python scrape_anichin_from_json.py

      - name: Commit & Push Results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add scraped_result.json
          # Tambahkan pengecekan agar tidak error jika tidak ada perubahan
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update scraped anime & video list"
            git push
          fi
