name: Scrape Anichin Iframe

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scrape.py

      - name: Commit and Push Results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add result.json
          git commit -m "Update result.json"
          git push
