name: Scrape Anichin Anime List & Video

on:
  workflow_dispatch: # Bisa dijalankan manual dari GitHub UI
  schedule:
    - cron: '0 3 * * *' # (opsional) jalan setiap hari jam 3 pagi UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 requests

      - name: Run scraping script
        run: |
          python scrape_anichin_from_json.py

      - name: Commit & Push Results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add scraped_result.json
          git commit -m "Update scraped anime & video list"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
