name: Scrape Anichin With Proxy Rotation

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Chrome Browser
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install semua library yang dibutuhkan oleh kedua script
          pip install selenium-wire beautifulsoup4 requests

      - name: Check for Live Proxies
        id: check_proxies
        run: python check_proxies.py

      - name: Run Main Scraper with Rotation
        # Hanya jalan jika step 'check_proxies' berhasil
        if: steps.check_proxies.outcome == 'success'
        run: python scrape_anichin.py # Nama script utama kita
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Commit & Push Results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add scraped_result.json
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Update: Scraped anime list with proxy rotation"
            git push
          fi
