name: Scrape Episodes

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps ( tanpa lock-file )
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        run: npm run scrape

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add episodes.json
          git diff --quiet && git diff --staged --quiet || git commit -m "🔄 auto-update episodes.json"
          git push
          
