name: Scrape Anichin List Mode

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Scrapy
        run: pip install scrapy

      - name: Run Scrapy Spider
        run: scrapy runspider anichin_listmode_spider.py -o hasil.json

      - name: Upload hasil scraping
        uses: actions/upload-artifact@v4
        with:
          name: hasil-scraping
          path: hasil.json
